name: oportunidades_cce
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: ^8.0.0
  connectivity_plus: ^1.1.0
  device_info_plus: ^2.1.0
  email_validator: ^2.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  # flutter_html: ^2.2.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.0.10+1
  flutter_tailwindcss_defaults: ^0.2.0
  get_it: ^7.2.0
  google_fonts: ^6.2.1
  html: ^0.15.0
  html_unescape: ^2.0.0
  http: ^1.2.1
  implicitly_animated_reorderable_list: ^0.4.1
  intl: ^0.18.0
  provider: ^6.0.0
  share_plus: ^2.1.4
  url_launcher: ^6.0.11

  flutter_gen: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon-1024x1024.png"
  image_path_ios: "assets/icon/icon-1024x1024-ios.png"
  remove_alpha_ios: true
